### ISSUE TITLE
Design for 'readyness'

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/simpervisor#3]
Steal from k8s' design of what being 'ready' means. 

For example, if we start RStudio, it is 'ready' when the webserver
can serve our requests.

**Comment by consideRatio** [comment]
Is this to be considered resolved thanks to accepting a `ready_func` when instanciating a SupervisedProcess object?

https://github.com/jupyterhub/simpervisor/blob/02f6db6cc64588408b964f70f20b49627840e174/simpervisor/process.py#L193-L213

**Comment by yuvipanda** [comment]
Yep!
