### ISSUE TITLE
Add missing git tags for 0.1 and 0.3 releases, and backfill changelog for 0.1, 0.2, 0.3, 0.4

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/simpervisor#35]
Looking at the PyPI releases i saw 0.1, 0.2, 0.3, 0.4, but only 0.2 and 0.4 as git tags in this repo.

- I'd like to retroactively add git tags (without republishing something) to this repo.
  There is an obvious commit that was made just before the PyPI release was registered for both 0.1 and 0.3.
  - [x] `v0.1` tag for 058e55ecef04daa0d907f78f27e81a5705f21afc
  - [x] `v0.3` tag for 08444aab7d74d114d6b53d9bd9985abbf15e4113
- [ ] Then I'd like to generate a changelog retroactively for 0.1, 0.2, 0.3, 0.4, and then finally 1.0.0 coming up.

**Comment by consideRatio** [comment]
@yuvipanda any objections to pushing these two tags retroactively?

**Comment by yuvipanda** [comment]
@consideRatio go for it!
